# Workflow name
name: 'Deploy with gh-pages'

# Event for the workflow
on: push

# List of jobs
jobs:
  test:
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - uses: actions/checkout@v1
      - run: npm i
      - name: build storybook
        run: npm run build-storybook
      - name: publish storybook
        run: npx gh-pages -d storybook-static
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
